### ISSUE TITLE
Non-Admin user is able to access all the data about other users 

### ISSUE THREAD

**Issue by ssinha2103** [rajeshsinha1997/Centralised_Banking_System_Application#3]
Hello @rajeshsinha1997 , I looked into your project and it's awesome . But I found a bug,-- Non-Admin user is able to access all the data about other users . #2 
I guess its a serious problem I guess. Please look into it.

**Comment by rajeshsinha1997** [comment]
CONFIRMED!
Will look into it 🙂

**Comment by rajeshsinha1997** [comment]
Fixed!

**Comment by rajeshsinha1997** [comment]
The bug is fixed
